// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDk65y1x8WZ60qGz-A_K1_qUD1nIcUTmbA',
    appId: '1:756483378471:web:0fddedca3e3661d067ed02',
    messagingSenderId: '756483378471',
    projectId: 'auth-f1d04',
    authDomain: 'auth-f1d04.firebaseapp.com',
    storageBucket: 'auth-f1d04.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDh__dz82Tj7B-Ovr23z4JnWYpFxBny5TU',
    appId: '1:756483378471:android:85fcdb835bcf776d67ed02',
    messagingSenderId: '756483378471',
    projectId: 'auth-f1d04',
    storageBucket: 'auth-f1d04.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCdHFvWzgNcBN_reDZElmFE2byRI-wrF3I',
    appId: '1:756483378471:ios:bafa1fb684fec93f67ed02',
    messagingSenderId: '756483378471',
    projectId: 'auth-f1d04',
    storageBucket: 'auth-f1d04.appspot.com',
    iosBundleId: 'com.example.authentication',
  );
}
